CREATE DATABASE IF NOT EXISTS userdata CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER IF NOT EXISTS 'freelanze'@'%' IDENTIFIED BY 'ren11261126';
GRANT ALL PRIVILEGES ON userdata.* TO 'freelanze'@'%';

FLUSH PRIVILEGES;